### ISSUE TITLE
Buscar, ver  y editar jugadores registrados 

### ISSUE THREAD

**Issue by Jmiguel14** [Jmiguel14/meet-goal-project#71]

**Comment by FreddyJR1995** [comment]
![image](https://user-images.githubusercontent.com/56648676/130307893-5a8f6e8f-9f39-4522-ade3-1623678f675c.png)

Se podría establecer un tamaño estándar para cada card, para que no exista esta distorsión al momento de tener uno o pocos resultados en nuestras búsquedas.
